In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../../data/job_postings_flat.csv')

In [5]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Data Analyst,"Summer Internship -Data Analyst Intern, Risk M...","Marlborough, MA",via Boatingrevealed.com,"Full-time, Part-time, and Internship",False,"New York, United States",2024-01-01 00:00:01,False,True,United States,NaN,NaN,NaN,BJ's Wholesale Club,['excel'],{'analyst_tools': ['excel']}
1,Data Analyst,"Staff Data Analyst Operations, Infrastructure ...","Fremont, CA",via ClimateTechList,Full-time,False,"California, United States",2024-01-01 00:00:11,True,False,United States,NaN,NaN,NaN,Tesla,"['tableau', 'flow']","{'analyst_tools': ['tableau'], 'other': ['flow']}"
2,Data Analyst,Junior Data Analyst - Entry Level,"Waco, TX",via ZipRecruiter,Full-time and Part-time,False,"Texas, United States",2024-01-01 00:00:15,True,False,United States,NaN,NaN,NaN,Next Recruiting,NaN,NaN
3,Data Analyst,"Data Analyst/Engineer, Supply Chain Optimizati...","Austin, TX",via ClimateTechList,Internship,False,"Texas, United States",2024-01-01 00:00:18,False,False,United States,NaN,NaN,NaN,Tesla,['spring'],{'libraries': ['spring']}
4,Data Scientist,It analyst,"Tampa, FL",via Talent.com,Full-time,False,"Florida, United States",2024-01-01 00:00:29,True,False,United States,NaN,NaN,NaN,VirtualVocations,NaN,NaN

In [6]:
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
478890,Data Scientist,ניהול ייצור ותעשייה | מדען נתונים Data Scientist,Israel,Mploy דרושים,Full-time,False,Israel,2024-12-31 23:33:50,False,False,Israel,NaN,NaN,NaN,Mploy דרושים,"['sql', 'matplotlib']","{'libraries': ['matplotlib'], 'programming': [..."
478891,Data Analyst,Business Data Analysis,"Columbia, SC",LinkedIn,Full-time,False,Georgia,2024-12-31 23:37:20,True,False,United States,NaN,NaN,NaN,Jobs via Dice,"['c#', 'sql', 'asp.net']","{'programming': ['c#', 'sql'], 'webframeworks'..."
478892,Machine Learning Engineer,"Vice President, Artificial Intelligence - Remo...","Bellflower, CA",Careers At The RealReal,Full-time,False,Georgia,2024-12-31 23:37:27,False,True,United States,NaN,NaN,NaN,The RealReal,NaN,NaN
478893,Data Engineer,Machine Learning Operations Data Engineer IV -...,"Cumberland, IN",WhatJobs,Full-time,False,Georgia,2024-12-31 23:37:33,False,True,United States,NaN,NaN,NaN,FM Global,"['sql', 'python', 'r', 'azure', 'databricks', ...","{'cloud': ['azure', 'databricks', 'aws', 'gcp'..."
478894,Data Engineer,Principal Data Engineer,"Ammon, ID",Snagajob,Full-time and Part-time,False,Georgia,2024-12-31 23:37:38,False,True,United States,NaN,NaN,NaN,Naval Nuclear Laboratory,NaN,NaN