In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
df = pd.read_csv('../../data/DS_Jobs_cleaned.csv')

In [27]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority,repeat_posting
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,0,0,0,0,1,0,0,data scientist,senior,0
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,0,0,1,0,0,0,1,data scientist,unspecified,0
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,1,1,0,0,1,0,0,data scientist,unspecified,0
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,1,1,0,0,1,0,0,data scientist,unspecified,0
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,1,1,0,0,0,0,0,data scientist,unspecified,0

In [30]:
df.isnull().sum()

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
min_salary           0
max_salary           0
avg_salary           0
job_state            0
same_state           0
company_age          0
python               0
excel                0
hadoop               0
spark                0
aws                  0
tableau              0
big_data             0
job_simp             0
seniority            0
repeat_posting       0
dtype: int64

In [29]:
df.shape

(648, 28)

In [28]:
df.tail()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority,repeat_posting
643,Data Scientist,105-167,Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,Company - Private,Advertising & Marketing,...,1,1,1,0,0,1,1,data scientist,unspecified,0
644,Data Scientist,105-167,Job Description\nBecome a thought leader withi...,3.8,JKGT,"San Francisco, CA",Unknown,Unknown,Unknown,Unknown,...,0,0,0,0,0,0,0,data scientist,unspecified,0
645,Data Scientist,105-167,Join a thriving company that is changing the w...,3.8,AccessHope,"Irwindale, CA",Unknown,Unknown,Unknown,Unknown,...,1,1,1,0,0,1,0,data scientist,unspecified,0
646,Data Scientist,105-167,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,Company - Private,Advertising & Marketing,...,1,0,1,1,0,0,1,data scientist,unspecified,0
647,Data Scientist,105-167,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,Company - Public,Wholesale,...,1,1,0,0,0,1,0,data scientist,unspecified,1